on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: pull code
        uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t karimlak/montreal_weather_api:latest .

      - name: Push Docker image
        run: docker push karimlak/montreal_weather_api:latest
  
  deploy:
    runs_on: ubuntu-latest
    needs: build
    steps:
      - name: pull code
        uses: actions/checkout@v3
      
      - name: Copy compose file to ec2
        uses: appleboy/scp-action@v0.1.7
          with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          source: "docker-compose.yml,infra.yml"
          target: "~/"
        script: |
                docker compose pull
                docker compose up -d


